field: f4540986-09ce-4a2e-b959-64d33257970b
fieldLayouts:
  99811d2e-d208-4e9a-becd-7da47cf2abdb:
    tabs:
      -
        elements:
          -
            fieldUid: c9269e0f-6c44-4a5d-a660-955d4ccc9d36
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: deff94ba-9c64-42c3-b696-27390b7f7c59
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 0cfa1e81-68d1-4480-81ad-a742cc0b7df7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  0cfa1e81-68d1-4480-81ad-a742cc0b7df7:
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColour
    instructions: ''
    name: 'Background colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Grey
            -
              - value
              - grey
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Orange
            -
              - value
              - orange
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Teal
            -
              - value
              - teal
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Navy
            -
              - value
              - navy
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c9269e0f-6c44-4a5d-a660-955d4ccc9d36:
    contentColumnType: string
    fieldGroup: null
    handle: relatedLocation
    instructions: ''
    name: 'Related Location'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Add a location'
      showSiteMenu: true
      source: null
      sources:
        - 'section:08146327-4163-41bb-a504-486728b5d87a'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  deff94ba-9c64-42c3-b696-27390b7f7c59:
    contentColumnType: string
    fieldGroup: null
    handle: highlightColour
    instructions: ''
    name: 'Highlight colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Orange
            -
              - value
              - orange
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Teal
            -
              - value
              - teal
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Navy
            -
              - value
              - navy
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: location
name: Location
sortOrder: 1
