field: 1b2dd889-a15f-4751-9490-c05ccf29e3a0
fieldLayouts:
  830e69bd-c585-474f-b01c-0948dd4ada64:
    tabs:
      -
        elements:
          -
            fieldUid: ab0128eb-c468-442a-8fe7-0768caa7bd66
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a213da3c-b102-485d-bcb5-2a5b5e0a114b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a213da3c-b102-485d-bcb5-2a5b5e0a114b:
    contentColumnType: text
    fieldGroup: null
    handle: milestoneText
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ab0128eb-c468-442a-8fe7-0768caa7bd66:
    contentColumnType: text
    fieldGroup: null
    handle: milestoneYear
    instructions: ''
    name: Year
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: milestones
name: Milestones
sortOrder: 1
