childBlocks: ''
field: 75b1acfe-7a14-4645-a4c4-81daf611bb15
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            heading: 'Global card settings'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 589e1009-2f9a-4d2c-aa26-593831c19473
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 0634d2f6-12b5-4100-90c7-9ffb979dc795
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: cb9d0ed4-3091-4e22-a387-086e48397ba9
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Add cards'
        sortOrder: 1
handle: card
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Card
sortOrder: 6
topLevel: false
