childBlocks: ''
field: 75b1acfe-7a14-4645-a4c4-81daf611bb15
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: 07dbcb9d-04fa-41e4-896c-9a8ecdcee9ae
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b3f4f89d-62f0-4831-8283-da448442002e
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Gallery and text'
        sortOrder: 1
handle: galleryAndText
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Gallery and text'
sortOrder: 11
topLevel: false
