childBlocks: ''
field: 75b1acfe-7a14-4645-a4c4-81daf611bb15
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: 8661f864-b883-4634-aa47-72f324894458
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1b2dd889-a15f-4751-9490-c05ccf29e3a0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0c8dcf49-0928-408d-845f-c364148d493f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: History
        sortOrder: 1
handle: history
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: History
sortOrder: 3
topLevel: false
