childBlocks: ''
field: 75b1acfe-7a14-4645-a4c4-81daf611bb15
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: 34c4af62-db58-41cd-af0f-1f79fd64f17e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Location logos'
        sortOrder: 1
handle: locationLogos
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Location logos'
sortOrder: 14
topLevel: false
