childBlocks: ''
field: 75b1acfe-7a14-4645-a4c4-81daf611bb15
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: f4540986-09ce-4a2e-b959-64d33257970b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Locations
        sortOrder: 1
handle: map
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Map
sortOrder: 14
topLevel: false
