childBlocks:
  - richText
  - textAndImage
  - splitScreen
  - card
  - iconCards
  - testimonials
  - apartments
  - galleryAndText
  - contactForm
  - spacer
  - map
field: 75b1acfe-7a14-4645-a4c4-81daf611bb15
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            heading: 'Section settings'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: a175f1f9-23f7-42a8-b864-9ad5425371e0
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: a6389e63-4575-4907-bad3-5588fbd0c3a0
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            heading: 'Section content'
            type: craft\fieldlayoutelements\Heading
        name: 'Page section settings'
        sortOrder: 1
handle: pageSection
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Section
sortOrder: 1
topLevel: true
