childBlocks: ''
field: 75b1acfe-7a14-4645-a4c4-81daf611bb15
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: d4841052-9964-4fca-b825-c721bb970063
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: e06d25bd-f577-42b6-9006-835ff5578494
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 432cd2ff-d465-41c9-b9ef-873ecc63866c
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: b3f4f89d-62f0-4831-8283-da448442002e
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6c67473b-6a70-40fc-9aee-5595e6bac9cd
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Split screen content'
        sortOrder: 1
handle: splitScreen
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Split screen'
sortOrder: 6
topLevel: false
