childBlocks: ''
field: 75b1acfe-7a14-4645-a4c4-81daf611bb15
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: b9347423-2474-434e-8820-ffdd695e300b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Testimonials
        sortOrder: 1
handle: testimonials
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Testimonials
sortOrder: 9
topLevel: false
