fieldLayouts:
  d5c30d29-4771-463c-974c-f79e809a1b30:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: b6185887-95b1-48a1-9f04-5a246d94bf56
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 62561434-a792-4514-a637-4a2e0a0c9f08
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Optimised image'
        sortOrder: 1
handle: uploads
hasUrls: true
name: Uploads
settings:
  bucket: $DO_BUCKET
  contentDisposition: ''
  endpoint: $DO_ENDPOINT
  expires: '3 months'
  keyId: $DO_ACCESS_KEY
  region: $DO_REGION
  secret: $DO_SECRET_KEY
  subfolder: bethany/website-assets
sortOrder: 1
type: vaersaagod\dospaces\Volume
url: $DO_BASE_URL
