contentColumnType: boolean
fieldGroup: 49a83f2f-08f9-4254-aafe-ba496e1a2835
handle: addShadow
instructions: ''
name: 'Add shadow'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
