contentColumnType: string
fieldGroup: 49a83f2f-08f9-4254-aafe-ba496e1a2835
handle: buttons
instructions: ''
name: Buttons
searchable: true
settings:
  contentTable: '{{%matrixcontent_buttons}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
