contentColumnType: string
fieldGroup: 49a83f2f-08f9-4254-aafe-ba496e1a2835
handle: cardWidth
instructions: ''
name: 'Card width'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - w-1/4
        -
          - value
          - '4'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - w-1/3
        -
          - value
          - '3'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - w-1/2
        -
          - value
          - '2'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - full
        -
          - value
          - '1'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
