contentColumnType: text
fieldGroup: a6aefed7-bddd-4c9f-b795-b129df67863f
handle: featureVideo
instructions: 'Place the embed code here.'
name: 'Feature video'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
