contentColumnType: string
fieldGroup: 49a83f2f-08f9-4254-aafe-ba496e1a2835
handle: forms
instructions: ''
name: Forms
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: verbb\formie\fields\Forms
