contentColumnType: text
fieldGroup: 854c4e69-53a0-48a2-9639-0593b3676701
handle: positionLinkText
instructions: 'What do you want the apply now button to say?'
name: 'Position link text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Apply now!'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
