contentColumnType: string
fieldGroup: 80f56823-f927-4033-b054-87d676e03e54
handle: seoImage
instructions: ''
name: 'SEO Image'
searchable: true
settings:
  allowSelfRelations: ''
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:b2e06900-60b6-4e7a-9d8e-ab52b6fed571'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add an image'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:b2e06900-60b6-4e7a-9d8e-ab52b6fed571'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
