contentColumnType: text
fieldGroup: 80f56823-f927-4033-b054-87d676e03e54
handle: seoTitle
instructions: ''
name: 'SEO Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
