contentColumnType: text
fieldGroup: 49a83f2f-08f9-4254-aafe-ba496e1a2835
handle: videoCode
instructions: ''
name: 'Video code'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
