dateModified: 1623639775
email:
  fromEmail: contact.bethany@bethanycc.org.au
  fromName: 'Bethany Christian Care'
  replyToEmail: kimberly.mcdonald@bethanycc.org.au
  template: ''
  transportSettings:
    encryptionMethod: tls
    host: smtp.office365.com
    password: Bay63922
    port: '587'
    timeout: '10'
    useAuthentication: '1'
    username: contact.bethany@bethanycc.org.au
  transportType: craft\mail\transportadapters\Smtp
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: 'On behalf of'
      prependSubject: 'New message from Bethany Christian Care'
      successFlashMessage: 'Your message has been sent.'
      toEmail: ryan@newwordorder.com.au
  cp-css:
    edition: standard
    enabled: false
    schemaVersion: 2.0.0
    settings:
      additionalCss: ''
      cssFile: /dist/css/redactor.css
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: TAZTG4GWRQUKTMDUR7V2FFDE
    schemaVersion: 1.1.11
    settings:
      alertEmails:
        -
          - 'Ryan Murray'
          - ryan@newwordorder.com.au
        -
          - 'Kimberly McDonald'
          - kimberly.mcdonald@bethanycc.org.au
      captchas:
        duplicate:
          enabled: false
          settings:
            handle: duplicate
          type: verbb\formie\integrations\captchas\Duplicate
        honeypot:
          enabled: false
          settings:
            handle: honeypot
          type: verbb\formie\integrations\captchas\Honeypot
        javascript:
          enabled: false
          settings:
            handle: javascript
          type: verbb\formie\integrations\captchas\Javascript
        recaptcha:
          enabled: true
          settings:
            badge: bottomright
            handle: recaptcha
            language: en-GB
            minScore: '0.5'
            secretKey: $RECAPTCHA_SECRET_KEY
            siteKey: $RECAPTCHA_SITE_KEY
            size: normal
            theme: light
            type: v3
          type: verbb\formie\integrations\captchas\Recaptcha
      defaultDateDisplayType: ''
      defaultDateTime: null
      defaultDateValueOption: ''
      defaultEmailTemplate: ''
      defaultFileUploadVolume: ''
      defaultFormTemplate: ''
      defaultInstructionsPosition: verbb\formie\positions\BelowInput
      defaultLabelPosition: verbb\formie\positions\AboveInput
      defaultPage: forms
      enableUnloadWarning: true
      maxIncompleteSubmissionAge: 30
      pluginName: Formie
      saveSpam: false
      sendEmailAlerts: '1'
      spamBehaviour: showSuccess
      spamBehaviourMessage: ''
      spamKeywords: ''
      spamLimit: 500
      useQueueForIntegrations: true
      useQueueForNotifications: true
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: DS468OB9EIYSW9KESOIOWFV6
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: true
      assetVolumeSubFolders: true
      autoSharpenScaledImages: true
      createColorPalette: true
      createPlaceholderSilhouettes: false
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
      lowerQualityRetinaImageVariants: true
      transformClass: nystudio107\imageoptimize\imagetransforms\CraftImageTransform
  navigation:
    edition: standard
    enabled: true
    licenseKey: RMP62XFZYSUHBGXR3N8SFTG8
    schemaVersion: 1.0.21
  neo:
    edition: standard
    enabled: true
    licenseKey: UEQQVZVRFS1ALJ5ZP7XJMFLO
    schemaVersion: 2.9.11
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: false
    schemaVersion: 1.0.0
  seeder:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: TW4N37KVZBKCPIM8PV78O6MC
    schemaVersion: 3.0.10
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      generatorEnabled: true
      headersEnabled: true
      lowercaseCanonicalUrl: '1'
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  wordsmith:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
system:
  edition: pro
  live: true
  name: 'Bethany Christian Care'
  schemaVersion: 3.6.8
  timeZone: Australia/Brisbane
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
