dateModified: 1596600672
email:
  fromEmail: ryan@newwordorder.com.au
  fromName: 'Bethany Christian Care'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  blitz-recommendations:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: 'On behalf of'
      prependSubject: 'New message from Bethany Christian Care'
      successFlashMessage: 'Your message has been sent.'
      toEmail: ryan@newwordorder.com.au
  cp-css:
    edition: standard
    enabled: false
    schemaVersion: 2.0.0
    settings:
      additionalCss: ''
      cssFile: /dist/css/redactor.css
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-optimize:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: true
      assetVolumeSubFolders: true
      autoSharpenScaledImages: true
      createColorPalette: true
      createPlaceholderSilhouettes: false
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
      lowerQualityRetinaImageVariants: true
      transformClass: nystudio107\imageoptimize\imagetransforms\CraftImageTransform
  navigation:
    edition: standard
    enabled: true
    schemaVersion: 1.0.17
  neo:
    edition: standard
    enabled: true
    schemaVersion: 2.8.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: false
    schemaVersion: 1.0.0
  seeder:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.9
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  wordsmith:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
system:
  edition: pro
  live: true
  name: 'Bethany Christian Care'
  schemaVersion: 3.5.12
  timeZone: Australia/Brisbane
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
