field: 75b1acfe-7a14-4645-a4c4-81daf611bb15
fieldLayouts:
  0af7f367-5544-4147-abc8-9fd06f0a66a9:
    tabs:
      -
        fields:
          3ec2723e-0656-4f9d-9645-9c8937567742:
            required: false
            sortOrder: 3
          39d2fc44-e08e-4fb1-9fc4-27e15d6765c0:
            required: false
            sortOrder: 1
          757aa51b-fe76-46f7-914b-648129791cec:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  3ec2723e-0656-4f9d-9645-9c8937567742:
    contentColumnType: string
    fieldGroup: null
    handle: spacing
    instructions: ''
    name: Spacing
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
            -
              - default
              - none
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - py-8
            -
              - default
              - py-8
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - py-16
            -
              - default
              - py-16
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - py-32
            -
              - default
              - py-32
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  39d2fc44-e08e-4fb1-9fc4-27e15d6765c0:
    contentColumnType: string
    fieldGroup: null
    handle: pageSection
    instructions: ''
    name: Section
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_pagesection}}'
      maxBlocks: ''
      minBlocks: ''
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  757aa51b-fe76-46f7-914b-648129791cec:
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColour
    instructions: ''
    name: 'Background colour'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - bg-white
            -
              - default
              - bg-white
        -
          __assoc__:
            -
              - label
              - Navy
            -
              - value
              - bg-navy-500
            -
              - default
              - bg-navy-500
        -
          __assoc__:
            -
              - label
              - Grey
            -
              - value
              - bg-grey-500
            -
              - default
              - bg-grey-500
        -
          __assoc__:
            -
              - label
              - Pink
            -
              - value
              - bg-pink-500
            -
              - default
              - bg-pink-500
        -
          __assoc__:
            -
              - label
              - Teal
            -
              - value
              - bg-teal-500
            -
              - default
              - bg-teal-500
        -
          __assoc__:
            -
              - label
              - Orange
            -
              - value
              - bg-orange-500
            -
              - default
              - bg-orange-500
        -
          __assoc__:
            -
              - label
              - 'Callout BG'
            -
              - value
              - bg-calloutBg
            -
              - default
              - bg-calloutBg
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
